
all:

install:
	@if not exist C:\python24\Lib\site-packages\PyQt4\elementtree mkdir C:\python24\Lib\site-packages\PyQt4\elementtree
	copy /y .\ElementPath.py C:\python24\Lib\site-packages\PyQt4\elementtree\ElementPath.py
	copy /y .\ElementTree.py C:\python24\Lib\site-packages\PyQt4\elementtree\ElementTree.py
	copy /y .\__init__.py C:\python24\Lib\site-packages\PyQt4\elementtree\__init__.py

clean:
